import { Streamer, Shift, Schedule, LiveSession, KPITarget, ProductCatalog } from '../types';

export const INITIAL_SHIFTS: Shift[] = [
  {
    id: 'shift-1',
    name: 'Shift 1 (Pagi)',
    code: 'SHIFT 1',
    startTime: '06:00',
    endTime: '12:00',
    durationHours: 6,
    isOvernight: false,
  },
  {
    id: 'shift-2',
    name: 'Shift 2 (Siang - Sore)',
    code: 'SHIFT 2',
    startTime: '12:00',
    endTime: '18:00',
    durationHours: 6,
    isOvernight: false,
  },
  {
    id: 'shift-3',
    name: 'Shift 3 (Malam / Prime Time)',
    code: 'SHIFT 3',
    startTime: '18:00',
    endTime: '24:00',
    durationHours: 6,
    isOvernight: false,
  },
  {
    id: 'shift-4',
    name: 'Shift 4 (Tengah Malam / Subuh)',
    code: 'SHIFT EXTRA',
    startTime: '00:00',
    endTime: '06:00',
    durationHours: 6,
    isOvernight: true,
  },
];

export const INITIAL_STREAMERS: Streamer[] = [
  {
    id: 'str-1',
    name: 'Nadia Safitri',
    email: 'nadia.safitri@shopeelive.id',
    phone: '0812-3456-7890',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    joinDate: '2024-01-15',
    notes: 'Spesialis Fashion Muslim & Beauty. Sangat komunikatif dan responsif dengan penonton keranjang kuning.',
    totalRevenue: 84500000,
    totalOrders: 642,
    totalHours: 72,
    averageCvr: 6.8,
  },
  {
    id: 'str-2',
    name: 'Rian Hidayat',
    email: 'rian.hidayat@shopeelive.id',
    phone: '0813-9876-5432',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    joinDate: '2024-02-01',
    notes: 'Kuat di demo produk elektronik, aksesoris smartphone & outfit casual pria.',
    totalRevenue: 62800000,
    totalOrders: 490,
    totalHours: 66,
    averageCvr: 5.4,
  },
  {
    id: 'str-3',
    name: 'Cindy Claudia',
    email: 'cindy.claudia@shopeelive.id',
    phone: '0821-4567-8901',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    joinDate: '2024-02-15',
    notes: 'Top host Skincare & Makeup. Memiliki gaya bicara energik dan persuasif saat flash sale voucher.',
    totalRevenue: 98200000,
    totalOrders: 780,
    totalHours: 78,
    averageCvr: 8.2,
  },
  {
    id: 'str-4',
    name: 'Daffa Pratama',
    email: 'daffa.pratama@shopeelive.id',
    phone: '0857-1234-5678',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    joinDate: '2024-03-01',
    notes: 'Handal di sesi live malam hari & interaksi kuis giveaway.',
    totalRevenue: 47600000,
    totalOrders: 375,
    totalHours: 54,
    averageCvr: 5.1,
  },
  {
    id: 'str-5',
    name: 'Sarah Amalia',
    email: 'sarah.amalia@shopeelive.id',
    phone: '0878-6543-2109',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    joinDate: '2024-04-10',
    notes: 'Fokus pada perlengkapan rumah tangga, koper & perabot estetik.',
    totalRevenue: 38400000,
    totalOrders: 310,
    totalHours: 48,
    averageCvr: 4.9,
  },
];

export const INITIAL_PRODUCTS: ProductCatalog[] = [
  { id: 'p-1', name: 'Glow Whitening Serum 30ml', sku: 'SKIN-GLOW-01', category: 'Beauty & Skincare', price: 89000, status: 'active' },
  { id: 'p-2', name: 'Gamis Rayon Twill Premium Busui', sku: 'FASH-GAMIS-02', category: 'Fashion Muslim', price: 145000, status: 'active' },
  { id: 'p-3', name: 'Kaos Polos Heavyweight Cotton Combed 24s', sku: 'FASH-TEE-03', category: 'Fashion Pria', price: 65000, status: 'active' },
  { id: 'p-4', name: 'Velvet Lip Tint Hydrating Longwear', sku: 'BEAUTY-LIP-04', category: 'Makeup', price: 49000, status: 'active' },
  { id: 'p-5', name: 'Wireless Bluetooth Earphone ANC TWS', sku: 'ELEC-TWS-05', category: 'Gadget & Elektronik', price: 179000, status: 'active' },
  { id: 'p-6', name: 'Tas Selempang Wanita Kulit Sintetis Import', sku: 'BAG-CROSS-06', category: 'Tas & Aksesoris', price: 115000, status: 'active' },
  { id: 'p-7', name: 'Sunscreen UV Shield Gel SPF 50 PA++++', sku: 'SKIN-SUN-07', category: 'Beauty & Skincare', price: 75000, status: 'active' },
];

// Helper to format date strings relative to today
const getRelativeDate = (offsetDays: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_SESSIONS: LiveSession[] = [
  {
    id: 'sess-shopee-real',
    streamerId: 'str-1',
    streamerName: 'Nadia Safitri',
    businessDate: getRelativeDate(0),
    shiftId: 'shift-1',
    shiftName: 'Shift 1 (Pagi)',
    startTime: '06:00',
    endTime: '12:00',
    durationMinutes: 360,
    durationHours: 6.0,
    
    // Exact Shopee Wawasan Livestream from Screenshot
    orderStatus: 'Pesanan Dibuat',
    revenue: 1243800,
    activeViewers: 412,
    comments: 24,
    addToCart: 72,
    
    // Baris 1
    totalViews: 3061,
    viewers: 3061,
    avgWatchDuration: '00:00:35',
    commentRate: 0.8,
    rpm: 406338,
    orders: 11,
    averageOrderValue: 113073,

    // Baris 2
    uniqueViewers: 2643,
    peakViewers: 101,
    averageViewers: 412,
    clickRate: 3.7,
    conversionRate: 9.7,
    buyers: 11,
    productsSold: 23,

    // Engagement & Funnel
    likes: 12400,
    shares: 45,
    newFollowers: 68,
    productImpressions: 3061,
    productClicks: 72,
    checkout: 18,
    voucherUsed: 8,
    cancelledOrders: 0,
    refundOrders: 0,
    refundAmount: 0,
    affiliateOrders: 2,
    affiliateRevenue: 226000,
    adsSpend: 80000,
    revenuePerHour: 207300,
    ordersPerHour: 1.83,
    viewersPerHour: 510,
    revenuePerViewer: 471,
    products: [
      { sku: 'FASH-GAMIS-02', productName: 'Gamis Rayon Twill Premium Busui', quantity: 12, price: 65000, revenue: 780000 },
      { sku: 'FASH-TEE-03', productName: 'Kaos Polos Heavyweight Cotton Combed', quantity: 11, price: 42163, revenue: 463800 },
    ],
    notes: 'Sesuai data Shopee Live Wawasan Livestream: 11 pesanan dihasilkan dari 72 klik keranjang (Pesanan per klik 9.7%). Penonton tertinggi 101 pada saat spill produk diskon pagi.',
    isDemo: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'sess-001',
    streamerId: 'str-3',
    streamerName: 'Cindy Claudia',
    businessDate: getRelativeDate(0),
    shiftId: 'shift-3',
    shiftName: 'Shift 3 (Malam / Prime Time)',
    startTime: '18:00',
    endTime: '24:00',
    durationMinutes: 360,
    durationHours: 6.0,
    revenue: 16850000,
    orders: 142,
    productsSold: 198,
    averageOrderValue: 118662,
    viewers: 14800,
    uniqueViewers: 11200,
    peakViewers: 1250,
    averageViewers: 580,
    likes: 85200,
    comments: 4210,
    shares: 620,
    newFollowers: 485,
    productImpressions: 22400,
    productClicks: 2150,
    checkout: 295,
    conversionRate: 6.6,
    voucherUsed: 88,
    cancelledOrders: 4,
    refundOrders: 1,
    refundAmount: 145000,
    affiliateOrders: 18,
    affiliateRevenue: 2450000,
    adsSpend: 450000,
    revenuePerHour: 2808333,
    ordersPerHour: 23.7,
    viewersPerHour: 2466,
    revenuePerViewer: 1138,
    products: [
      { sku: 'BEAUTY-LIP-04', productName: 'Velvet Lip Tint Hydrating Longwear', quantity: 95, price: 49000, revenue: 4655000 },
      { sku: 'SKIN-GLOW-01', productName: 'Glow Whitening Serum 30ml', quantity: 62, price: 89000, revenue: 5518000 },
      { sku: 'SKIN-SUN-07', productName: 'Sunscreen UV Shield Gel SPF 50', quantity: 41, price: 75000, revenue: 3075000 },
    ],
    notes: 'Traffic prime time sangat tinggi pada pukul 20:00 - 22:00. Voucher toko 10k habis dalam 30 menit. Penonton sangat antusias saat swatch warna lip tint.',
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sess-002',
    streamerId: 'str-1',
    streamerName: 'Nadia Safitri',
    businessDate: getRelativeDate(0),
    shiftId: 'shift-2',
    shiftName: 'Shift 2 (Siang - Sore)',
    startTime: '12:00',
    endTime: '18:00',
    durationMinutes: 360,
    durationHours: 6.0,
    revenue: 11420000,
    orders: 86,
    productsSold: 112,
    averageOrderValue: 132790,
    viewers: 8900,
    uniqueViewers: 6400,
    peakViewers: 620,
    averageViewers: 310,
    likes: 42300,
    comments: 2100,
    shares: 280,
    newFollowers: 220,
    productImpressions: 14200,
    productClicks: 1480,
    checkout: 165,
    conversionRate: 5.8,
    voucherUsed: 52,
    cancelledOrders: 2,
    refundOrders: 0,
    refundAmount: 0,
    affiliateOrders: 10,
    affiliateRevenue: 1280000,
    adsSpend: 250000,
    revenuePerHour: 1903333,
    ordersPerHour: 14.3,
    viewersPerHour: 1483,
    revenuePerViewer: 1283,
    products: [
      { sku: 'FASH-GAMIS-02', productName: 'Gamis Rayon Twill Premium Busui', quantity: 54, price: 145000, revenue: 7830000 },
      { sku: 'BAG-CROSS-06', productName: 'Tas Selempang Wanita Kulit Sintetis', quantity: 31, price: 115000, revenue: 3565000 },
    ],
    notes: 'Sesi berjalan mulus, Gamis Rayon ukuran XL paling cepat laku. Pukul 14:00 - 15:30 ada penurunan traffic wajar jam kantor.',
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sess-003',
    streamerId: 'str-2',
    streamerName: 'Rian Hidayat',
    businessDate: getRelativeDate(0),
    shiftId: 'shift-1',
    shiftName: 'Shift 1 (Pagi)',
    startTime: '06:00',
    endTime: '12:00',
    durationMinutes: 360,
    durationHours: 6.0,
    revenue: 8950000,
    orders: 74,
    productsSold: 88,
    averageOrderValue: 120945,
    viewers: 7200,
    uniqueViewers: 5100,
    peakViewers: 450,
    averageViewers: 220,
    likes: 31200,
    comments: 1450,
    shares: 190,
    newFollowers: 140,
    productImpressions: 11500,
    productClicks: 1220,
    checkout: 130,
    conversionRate: 6.0,
    voucherUsed: 38,
    cancelledOrders: 1,
    refundOrders: 0,
    refundAmount: 0,
    affiliateOrders: 6,
    affiliateRevenue: 850000,
    adsSpend: 200000,
    revenuePerHour: 1491666,
    ordersPerHour: 12.3,
    viewersPerHour: 1200,
    revenuePerViewer: 1243,
    products: [
      { sku: 'ELEC-TWS-05', productName: 'Wireless Bluetooth Earphone ANC TWS', quantity: 38, price: 179000, revenue: 6802000 },
      { sku: 'FASH-TEE-03', productName: 'Kaos Polos Heavyweight Cotton Combed', quantity: 33, price: 65000, revenue: 2145000 },
    ],
    notes: 'Traffic pagi ramai saat penonton perjalanan berangkat kerja (jam 07:00 - 08:30). Earphone TWS sangat diminati saat demo bass suara.',
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sess-004',
    streamerId: 'str-4',
    streamerName: 'Daffa Pratama',
    businessDate: getRelativeDate(-1),
    shiftId: 'shift-3',
    shiftName: 'Shift 3 (Malam / Prime Time)',
    startTime: '18:00',
    endTime: '24:00',
    durationMinutes: 360,
    durationHours: 6.0,
    revenue: 12600000,
    orders: 110,
    productsSold: 145,
    averageOrderValue: 114545,
    viewers: 11200,
    uniqueViewers: 8200,
    peakViewers: 890,
    averageViewers: 420,
    likes: 58000,
    comments: 2900,
    shares: 410,
    newFollowers: 310,
    productImpressions: 17800,
    productClicks: 1890,
    checkout: 210,
    conversionRate: 5.8,
    voucherUsed: 65,
    cancelledOrders: 3,
    refundOrders: 1,
    refundAmount: 65000,
    affiliateOrders: 12,
    affiliateRevenue: 1540000,
    adsSpend: 350000,
    revenuePerHour: 2100000,
    ordersPerHour: 18.3,
    viewersPerHour: 1866,
    revenuePerViewer: 1125,
    products: [
      { sku: 'FASH-TEE-03', productName: 'Kaos Polos Heavyweight Cotton Combed', quantity: 95, price: 65000, revenue: 6175000 },
      { sku: 'ELEC-TWS-05', productName: 'Wireless Bluetooth Earphone ANC TWS', quantity: 36, price: 179000, revenue: 6444000 },
    ],
    notes: 'Sesi prime time kemarin sukses. Paket hemat 3 kaos langsung ludes.',
    isDemo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sess-005',
    streamerId: 'str-5',
    streamerName: 'Sarah Amalia',
    businessDate: getRelativeDate(-1),
    shiftId: 'shift-2',
    shiftName: 'Shift 2 (Siang - Sore)',
    startTime: '12:00',
    endTime: '18:00',
    durationMinutes: 360,
    durationHours: 6.0,
    revenue: 8200000,
    orders: 68,
    productsSold: 82,
    averageOrderValue: 120588,
    viewers: 6400,
    uniqueViewers: 4800,
    peakViewers: 420,
    averageViewers: 210,
    likes: 29000,
    comments: 1100,
    shares: 160,
    newFollowers: 130,
    productImpressions: 9800,
    productClicks: 1150,
    checkout: 118,
    conversionRate: 5.9,
    voucherUsed: 42,
    cancelledOrders: 1,
    refundOrders: 0,
    refundAmount: 0,
    affiliateOrders: 5,
    affiliateRevenue: 620000,
    adsSpend: 180000,
    revenuePerHour: 1366666,
    ordersPerHour: 11.3,
    viewersPerHour: 1066,
    revenuePerViewer: 1281,
    products: [
      { sku: 'BAG-CROSS-06', productName: 'Tas Selempang Wanita Kulit Sintetis', quantity: 45, price: 115000, revenue: 5175000 },
      { sku: 'SKIN-SUN-07', productName: 'Sunscreen UV Shield Gel SPF 50', quantity: 40, price: 75000, revenue: 3000000 },
    ],
    isDemo: true,
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_SCHEDULES: Schedule[] = [
  // Today's schedules
  {
    id: 'sch-01',
    date: getRelativeDate(0),
    streamerId: 'str-2',
    streamerName: 'Rian Hidayat',
    shiftId: 'shift-1',
    shiftName: 'Shift 1 (Pagi)',
    startTime: '06:00',
    endTime: '12:00',
    status: 'Completed',
    hasReport: true,
    reportId: 'sess-003',
  },
  {
    id: 'sch-02',
    date: getRelativeDate(0),
    streamerId: 'str-1',
    streamerName: 'Nadia Safitri',
    shiftId: 'shift-2',
    shiftName: 'Shift 2 (Siang - Sore)',
    startTime: '12:00',
    endTime: '18:00',
    status: 'Completed',
    hasReport: true,
    reportId: 'sess-002',
  },
  {
    id: 'sch-03',
    date: getRelativeDate(0),
    streamerId: 'str-3',
    streamerName: 'Cindy Claudia',
    shiftId: 'shift-3',
    shiftName: 'Shift 3 (Malam / Prime Time)',
    startTime: '18:00',
    endTime: '24:00',
    status: 'Completed',
    hasReport: true,
    reportId: 'sess-001',
  },
  {
    id: 'sch-04',
    date: getRelativeDate(0),
    streamerId: 'str-4',
    streamerName: 'Daffa Pratama',
    shiftId: 'shift-4',
    shiftName: 'Shift 4 (Tengah Malam / Subuh)',
    startTime: '00:00',
    endTime: '06:00',
    status: 'Live',
    hasReport: false,
    notes: 'Shift malam ekstra. Siapkan playlist background musik rileks.',
  },
  // Tomorrow's schedules
  {
    id: 'sch-05',
    date: getRelativeDate(1),
    streamerId: 'str-5',
    streamerName: 'Sarah Amalia',
    shiftId: 'shift-1',
    shiftName: 'Shift 1 (Pagi)',
    startTime: '06:00',
    endTime: '12:00',
    status: 'Scheduled',
    hasReport: false,
  },
  {
    id: 'sch-06',
    date: getRelativeDate(1),
    streamerId: 'str-2',
    streamerName: 'Rian Hidayat',
    shiftId: 'shift-2',
    shiftName: 'Shift 2 (Siang - Sore)',
    startTime: '12:00',
    endTime: '18:00',
    status: 'Scheduled',
    hasReport: false,
  },
  {
    id: 'sch-07',
    date: getRelativeDate(1),
    streamerId: 'str-1',
    streamerName: 'Nadia Safitri',
    shiftId: 'shift-3',
    shiftName: 'Shift 3 (Malam / Prime Time)',
    startTime: '18:00',
    endTime: '24:00',
    status: 'Scheduled',
    hasReport: false,
  },
  // Day after tomorrow
  {
    id: 'sch-08',
    date: getRelativeDate(2),
    streamerId: 'str-3',
    streamerName: 'Cindy Claudia',
    shiftId: 'shift-3',
    shiftName: 'Shift 3 (Malam / Prime Time)',
    startTime: '18:00',
    endTime: '24:00',
    status: 'Scheduled',
    hasReport: false,
  },
  // Yesterday missed report test schedule (to show reminder warning!)
  {
    id: 'sch-09',
    date: getRelativeDate(-1),
    streamerId: 'str-5',
    streamerName: 'Sarah Amalia',
    shiftId: 'shift-1',
    shiftName: 'Shift 1 (Pagi)',
    startTime: '06:00',
    endTime: '12:00',
    status: 'Completed',
    hasReport: false, // Intentional missing report to test reminder
    notes: 'Perlu follow-up laporan sesi pagi kemarin!',
  }
];

export const INITIAL_TARGETS: KPITarget[] = [
  {
    id: 'tar-01',
    title: 'Target Omset Tim (Bulan Ini)',
    type: 'team',
    period: 'monthly',
    metric: 'revenue',
    targetValue: 350000000, // Rp 350 Juta
    currentValue: 245000000,
    year: 2026,
    month: 9,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
  },
  {
    id: 'tar-02',
    title: 'Target Pesanan Harian Tim',
    type: 'team',
    period: 'daily',
    metric: 'orders',
    targetValue: 300, // 300 orders/day
    currentValue: 270,
    year: 2026,
    startDate: getRelativeDate(0),
    endDate: getRelativeDate(0),
  },
  {
    id: 'tar-03',
    title: 'Target Omset Cindy Claudia (Bulan Ini)',
    type: 'individual',
    period: 'monthly',
    metric: 'revenue',
    streamerId: 'str-3',
    streamerName: 'Cindy Claudia',
    targetValue: 100000000, // Rp 100 Juta
    currentValue: 84000000,
    year: 2026,
    month: 9,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
  },
  {
    id: 'tar-04',
    title: 'Target Jam Live Nadia Safitri',
    type: 'individual',
    period: 'monthly',
    metric: 'hours',
    streamerId: 'str-1',
    streamerName: 'Nadia Safitri',
    targetValue: 100, // 100 Jam
    currentValue: 72,
    year: 2026,
    month: 9,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
  },
];
